// <auto-generated />
using System;
using DataAccess.Concrete.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20231020202500_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Concrete.AppOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("AppOperationClaims", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "AppUser"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "AppUserType"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Page"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "PageType"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Product"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "ProductType"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Contact"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("GsmNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("GsmNumber");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PasswordSalt");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ProfileImageUrl");

                    b.Property<Guid>("RefreshToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UserName");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeID");

                    b.ToTable("AppUsers", "dbo");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 845, DateTimeKind.Local).AddTicks(5306),
                            CreatedUserId = 1,
                            Email = "sadmin@gmail.com",
                            FirstName = "System",
                            GsmNumber = "",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            PasswordHash = new byte[] { 225, 3, 41, 212, 27, 163, 144, 34, 65, 192, 0, 39, 115, 140, 159, 144, 251, 50, 71, 95, 191, 218, 176, 255, 112, 143, 89, 136, 85, 139, 51, 120, 207, 141, 221, 127, 194, 156, 44, 94, 62, 9, 155, 91, 181, 212, 69, 165, 230, 182, 50, 176, 178, 76, 222, 128, 130, 159, 245, 12, 206, 124, 95, 89 },
                            PasswordSalt = new byte[] { 148, 30, 252, 220, 106, 53, 0, 170, 239, 145, 218, 23, 68, 238, 119, 49, 152, 42, 152, 30, 51, 137, 86, 131, 20, 16, 68, 34, 236, 228, 250, 133, 121, 136, 132, 215, 239, 128, 124, 13, 226, 3, 156, 183, 182, 224, 173, 142, 29, 25, 53, 83, 237, 52, 184, 93, 83, 26, 134, 119, 115, 253, 245, 183, 189, 231, 159, 36, 179, 189, 65, 135, 187, 236, 102, 95, 187, 251, 164, 10, 152, 49, 200, 160, 16, 133, 139, 21, 144, 124, 197, 188, 56, 208, 124, 32, 119, 36, 92, 239, 149, 96, 43, 84, 36, 150, 139, 142, 70, 194, 96, 149, 212, 112, 85, 139, 4, 124, 59, 171, 98, 120, 243, 55, 29, 74, 139, 108 },
                            ProfileImageUrl = "",
                            RefreshToken = new Guid("f8923e1a-0aeb-4dbb-9cd5-042bf68e194f"),
                            UserName = "sadmin",
                            UserTypeID = -1
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppUserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("UserTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUserTypes", "dbo");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 850, DateTimeKind.Local).AddTicks(8557),
                            CreatedUserId = -1,
                            IsActive = true,
                            IsDeleted = false,
                            UserTypeName = "System Admin"
                        },
                        new
                        {
                            Id = -2,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 850, DateTimeKind.Local).AddTicks(9019),
                            CreatedUserId = -1,
                            IsActive = true,
                            IsDeleted = false,
                            UserTypeName = "Admin"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppUserTypeAppOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppOperationClaimId")
                        .HasColumnType("int");

                    b.Property<int?>("AppUserTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OperationClaimID")
                        .HasColumnType("int")
                        .HasColumnName("OperationClaimId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("char(4)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    b.HasKey("Id");

                    b.HasIndex("AppOperationClaimId");

                    b.HasIndex("AppUserTypeId");

                    b.ToTable("AppUserTypeAppOperationClaims", "dbo");
                });

            modelBuilder.Entity("Entities.Concrete.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("DisplayOrder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("LanguageCode");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LanguageName");

                    b.HasKey("Id");

                    b.ToTable("Languages", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            LanguageCode = "tr-TR",
                            LanguageName = "Türkçe"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            LanguageCode = "en-EN",
                            LanguageName = "English"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("DisplayOrder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PageTypeID")
                        .HasColumnType("int")
                        .HasColumnName("PageTypeID");

                    b.Property<string>("PageURL")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PageURL");

                    b.Property<int?>("ParentPageID")
                        .HasColumnType("int")
                        .HasColumnName("ParentPageID");

                    b.HasKey("Id");

                    b.HasIndex("PageTypeID");

                    b.ToTable("Pages", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 3,
                            IsActive = true,
                            PageTypeID = 1,
                            PageURL = "#"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            IsActive = true,
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUser/List",
                            ParentPageID = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUser/Add",
                            ParentPageID = 2
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUser/Update",
                            ParentPageID = 2
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUser/Delete",
                            ParentPageID = 2
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUser/Detail",
                            ParentPageID = 2
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 1,
                            IsActive = true,
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserType/List",
                            ParentPageID = 1
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserType/Add",
                            ParentPageID = 7
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserType/Update",
                            ParentPageID = 7
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserType/Delete",
                            ParentPageID = 7
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserType/Detail",
                            ParentPageID = 7
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 1,
                            IsActive = true,
                            PageTypeID = 1,
                            PageURL = "/Admin/Page/List",
                            ParentPageID = 1
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/Page/Add",
                            ParentPageID = 12
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/Page/Update",
                            ParentPageID = 12
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/Page/Delete",
                            ParentPageID = 12
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/Page/Detail",
                            ParentPageID = 12
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 1,
                            IsActive = true,
                            PageTypeID = 1,
                            PageURL = "/Admin/PagePermisson/List",
                            ParentPageID = 1
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 1,
                            IsActive = true,
                            PageTypeID = 1,
                            PageURL = "#"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 1,
                            IsActive = true,
                            PageTypeID = 1,
                            PageURL = "/Admin/Product/List",
                            ParentPageID = 18
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/Product/Add",
                            ParentPageID = 19
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/Product/Update",
                            ParentPageID = 19
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/Product/Delete",
                            ParentPageID = 19
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/Product/Detail",
                            ParentPageID = 19
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 1,
                            IsActive = true,
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductType/List",
                            ParentPageID = 18
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductType/Add",
                            ParentPageID = 24
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductType/Update",
                            ParentPageID = 24
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductType/Delete",
                            ParentPageID = 24
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductType/Detail",
                            ParentPageID = 24
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 2,
                            IsActive = true,
                            PageTypeID = 1,
                            PageURL = "#"
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 1,
                            IsActive = true,
                            PageTypeID = 1,
                            PageURL = "/Admin/Contact/List",
                            ParentPageID = 29
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/Contact/Add",
                            ParentPageID = 30
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/Contact/Update",
                            ParentPageID = 30
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/Contact/Delete",
                            ParentPageID = 30
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 1,
                            IsActive = false,
                            PageTypeID = 1,
                            PageURL = "/Admin/Contact/Detail",
                            ParentPageID = 30
                        });
                });

            modelBuilder.Entity("Entities.Concrete.PageLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageID")
                        .HasColumnType("int")
                        .HasColumnName("LanguageID");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("MetaDescription");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("MetaKeywords");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("MetaTitle");

                    b.Property<int>("PageID")
                        .HasColumnType("int")
                        .HasColumnName("PageID");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PageName");

                    b.Property<string>("PageSeoURL")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PageSeoURL");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageID");

                    b.HasIndex("PageID");

                    b.ToTable("PageLanguages", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(6228),
                            CreatedUserId = -1,
                            IsActive = true,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 1,
                            PageName = "Sistem Ayarları",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8578),
                            CreatedUserId = -1,
                            IsActive = true,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 2,
                            PageName = "Kullanıcılar",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8706),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 3,
                            PageName = "Kullanıcılar",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8709),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 4,
                            PageName = "Kullanıcılar",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8711),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 5,
                            PageName = "Kullanıcılar",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8713),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 6,
                            PageName = "Kullanıcılar",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8715),
                            CreatedUserId = -1,
                            IsActive = true,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 7,
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8717),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 8,
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8719),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 9,
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8721),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 10,
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8723),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 11,
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8725),
                            CreatedUserId = -1,
                            IsActive = true,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 12,
                            PageName = "Sayfalar",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8727),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 13,
                            PageName = "Sayfalar",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8729),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 14,
                            PageName = "Sayfalar",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8731),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 15,
                            PageName = "Sayfalar",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8736),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 16,
                            PageName = "Sayfalar",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8739),
                            CreatedUserId = -1,
                            IsActive = true,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 17,
                            PageName = "Sayfa Yetkileri",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8741),
                            CreatedUserId = -1,
                            IsActive = true,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 18,
                            PageName = "Ürün",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8743),
                            CreatedUserId = -1,
                            IsActive = true,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 19,
                            PageName = "Ürünler",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8746),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 20,
                            PageName = "Ürünler",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8748),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 21,
                            PageName = "Ürünler",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8750),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 22,
                            PageName = "Ürünler",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8752),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 23,
                            PageName = "Ürünler",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8754),
                            CreatedUserId = -1,
                            IsActive = true,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 24,
                            PageName = "Ürün Tipleri",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8756),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 25,
                            PageName = "Ürün Tipleri",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8760),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 26,
                            PageName = "Ürün Tipleri",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8762),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 27,
                            PageName = "Ürün Tipleri",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8764),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 28,
                            PageName = "Ürün Tipleri",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8766),
                            CreatedUserId = -1,
                            IsActive = true,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 29,
                            PageName = "Genel Sayfalar",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8768),
                            CreatedUserId = -1,
                            IsActive = true,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 31,
                            PageName = "Hakkımızda",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8770),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 32,
                            PageName = "Hakkımızda",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8772),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 33,
                            PageName = "Hakkımızda",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8774),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 34,
                            PageName = "Hakkımızda",
                            PageSeoURL = ""
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2023, 10, 20, 23, 24, 59, 861, DateTimeKind.Local).AddTicks(8776),
                            CreatedUserId = -1,
                            IsActive = false,
                            IsDeleted = false,
                            LanguageID = 1,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageID = 35,
                            PageName = "Hakkımızda",
                            PageSeoURL = ""
                        });
                });

            modelBuilder.Entity("Entities.Concrete.PagePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppOperationClaimId")
                        .HasColumnType("int");

                    b.Property<int?>("AppUserTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OperationClaimID")
                        .HasColumnType("int")
                        .HasColumnName("OperationClaimID");

                    b.Property<int>("PageID")
                        .HasColumnType("int")
                        .HasColumnName("PageID");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    b.HasKey("Id");

                    b.HasIndex("AppOperationClaimId");

                    b.HasIndex("AppUserTypeId");

                    b.HasIndex("PageID");

                    b.ToTable("PagePermissons", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            IsActive = true,
                            IsDeleted = false,
                            OperationClaimID = 1,
                            PageID = 2,
                            UserTypeID = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            IsActive = true,
                            IsDeleted = false,
                            OperationClaimID = 1,
                            PageID = 3,
                            UserTypeID = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            IsActive = true,
                            IsDeleted = false,
                            OperationClaimID = 1,
                            PageID = 4,
                            UserTypeID = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            IsActive = true,
                            IsDeleted = false,
                            OperationClaimID = 1,
                            PageID = 5,
                            UserTypeID = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            IsActive = true,
                            IsDeleted = false,
                            OperationClaimID = 1,
                            PageID = 6,
                            UserTypeID = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            IsActive = true,
                            IsDeleted = false,
                            OperationClaimID = 1,
                            PageID = 7,
                            UserTypeID = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            IsActive = true,
                            IsDeleted = false,
                            OperationClaimID = 1,
                            PageID = 8,
                            UserTypeID = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            IsActive = true,
                            IsDeleted = false,
                            OperationClaimID = 1,
                            PageID = 9,
                            UserTypeID = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            IsActive = true,
                            IsDeleted = false,
                            OperationClaimID = 1,
                            PageID = 10,
                            UserTypeID = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            IsActive = true,
                            IsDeleted = false,
                            OperationClaimID = 1,
                            PageID = 11,
                            UserTypeID = 2
                        });
                });

            modelBuilder.Entity("Entities.Concrete.PageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PageTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PageTypeName");

                    b.HasKey("Id");

                    b.ToTable("PageTypes", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PageTypeName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PageTypeName = "Web"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppUser", b =>
                {
                    b.HasOne("Entities.Concrete.AppUserType", "AppUserType")
                        .WithMany("AppUsers")
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUserType");
                });

            modelBuilder.Entity("Entities.Concrete.AppUserTypeAppOperationClaim", b =>
                {
                    b.HasOne("Entities.Concrete.AppOperationClaim", "AppOperationClaim")
                        .WithMany("AppUserTypeAppOperationClaims")
                        .HasForeignKey("AppOperationClaimId");

                    b.HasOne("Entities.Concrete.AppUserType", "AppUserType")
                        .WithMany()
                        .HasForeignKey("AppUserTypeId");

                    b.Navigation("AppOperationClaim");

                    b.Navigation("AppUserType");
                });

            modelBuilder.Entity("Entities.Concrete.Page", b =>
                {
                    b.HasOne("Entities.Concrete.PageType", "PageType")
                        .WithMany("Pages")
                        .HasForeignKey("PageTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageType");
                });

            modelBuilder.Entity("Entities.Concrete.PageLanguage", b =>
                {
                    b.HasOne("Entities.Concrete.Language", "Language")
                        .WithMany("PageLanguages")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.Page", "Page")
                        .WithMany("PageLanguages")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Entities.Concrete.PagePermission", b =>
                {
                    b.HasOne("Entities.Concrete.AppOperationClaim", "AppOperationClaim")
                        .WithMany("PagePermissions")
                        .HasForeignKey("AppOperationClaimId");

                    b.HasOne("Entities.Concrete.AppUserType", "AppUserType")
                        .WithMany("PagePermissions")
                        .HasForeignKey("AppUserTypeId");

                    b.HasOne("Entities.Concrete.Page", "Page")
                        .WithMany("PagePermissions")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppOperationClaim");

                    b.Navigation("AppUserType");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Entities.Concrete.AppOperationClaim", b =>
                {
                    b.Navigation("AppUserTypeAppOperationClaims");

                    b.Navigation("PagePermissions");
                });

            modelBuilder.Entity("Entities.Concrete.AppUserType", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("PagePermissions");
                });

            modelBuilder.Entity("Entities.Concrete.Language", b =>
                {
                    b.Navigation("PageLanguages");
                });

            modelBuilder.Entity("Entities.Concrete.Page", b =>
                {
                    b.Navigation("PageLanguages");

                    b.Navigation("PagePermissions");
                });

            modelBuilder.Entity("Entities.Concrete.PageType", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
