// <auto-generated />
using System;
using DataAccess.Concrete.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20230122084954_seedData")]
    partial class seedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Concrete.AppOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("AppOperationClaims", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "AppUser"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "AppUserType"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Page"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "PageType"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Product"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "ProductType"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Contact"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppUserTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("GsmNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("GsmNumber");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PasswordSalt");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ProfileImageUrl");

                    b.Property<Guid>("RefreshToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UserName");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    b.HasKey("Id");

                    b.HasIndex("AppUserTypeId");

                    b.ToTable("AppUsers", "dbo");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedDate = new DateTime(2023, 1, 22, 11, 49, 54, 176, DateTimeKind.Local).AddTicks(4946),
                            CreatedUserId = 1,
                            Email = "sadmin@gmail.com",
                            FirstName = "System",
                            GsmNumber = "",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            PasswordHash = new byte[] { 56, 237, 149, 214, 83, 158, 251, 192, 97, 101, 61, 34, 163, 32, 10, 51, 217, 26, 70, 45, 99, 242, 11, 241, 40, 32, 224, 94, 165, 20, 116, 136, 90, 197, 211, 216, 68, 5, 201, 255, 215, 203, 109, 205, 175, 9, 96, 139, 119, 69, 64, 60, 147, 84, 137, 20, 243, 197, 129, 210, 239, 176, 12, 117 },
                            PasswordSalt = new byte[] { 119, 154, 224, 73, 110, 96, 158, 237, 34, 179, 217, 201, 255, 207, 35, 255, 69, 77, 148, 17, 29, 155, 239, 140, 147, 229, 126, 67, 11, 23, 123, 82, 189, 207, 3, 214, 198, 26, 233, 178, 78, 78, 157, 127, 58, 10, 53, 74, 68, 238, 123, 5, 7, 160, 129, 34, 54, 130, 29, 169, 132, 105, 158, 6, 78, 89, 118, 74, 51, 37, 87, 63, 108, 77, 12, 165, 75, 81, 77, 253, 138, 7, 225, 12, 70, 149, 157, 187, 20, 219, 236, 102, 249, 136, 241, 109, 97, 129, 190, 201, 242, 250, 7, 166, 49, 203, 218, 72, 132, 188, 58, 135, 144, 157, 143, 17, 179, 21, 122, 114, 156, 198, 62, 173, 63, 89, 117, 35 },
                            ProfileImageUrl = "",
                            RefreshToken = new Guid("0ea4e0b2-d5a6-462b-a479-127d5324a33c"),
                            UserName = "sadmin",
                            UserTypeID = -1
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppUserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UserTypeName");

                    b.HasKey("Id");

                    b.ToTable("AppUserTypes", "dbo");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = 0,
                            IsActive = true,
                            IsDeleted = false,
                            UserTypeName = "System Admin"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppUserTypeAppOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppOperationClaimId")
                        .HasColumnType("int");

                    b.Property<int?>("AppUserTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OperationClaimID")
                        .HasColumnType("int")
                        .HasColumnName("OperationClaimId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("char(4)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    b.HasKey("Id");

                    b.HasIndex("AppOperationClaimId");

                    b.HasIndex("AppUserTypeId");

                    b.ToTable("AppUserTypeAppOperationClaims", "dbo");
                });

            modelBuilder.Entity("Entities.Concrete.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("DisplayOrder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("MetaDescription");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("MetaKeywords");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("MetaTitle");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PageName");

                    b.Property<string>("PageSeoURL")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PageSeoURL");

                    b.Property<int>("PageTypeID")
                        .HasColumnType("int")
                        .HasColumnName("PageTypeID");

                    b.Property<string>("PageURL")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PageURL");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.HasKey("Id");

                    b.HasIndex("PageTypeID");

                    b.ToTable("Pages", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 3,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sistem Ayarları",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "#"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcılar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUser/List",
                            ParentID = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcılar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUser/Add",
                            ParentID = 2
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcılar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUser/Update",
                            ParentID = 2
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcılar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUser/Delete",
                            ParentID = 2
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcılar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUser/Detail",
                            ParentID = 2
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserType/List",
                            ParentID = 1
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserType/Add",
                            ParentID = 7
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserType/Update",
                            ParentID = 7
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserType/Delete",
                            ParentID = 7
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Kullanıcı Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/AppUserType/Detail",
                            ParentID = 7
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sayfalar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Page/List",
                            ParentID = 1
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sayfalar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Page/Add",
                            ParentID = 12
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sayfalar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Page/Update",
                            ParentID = 12
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sayfalar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Page/Delete",
                            ParentID = 12
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sayfalar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Page/Detail",
                            ParentID = 12
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Sayfa Yetkileri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/PagePermisson/List",
                            ParentID = 1
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürün",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "#"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürünler",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Product/List",
                            ParentID = 18
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürünler",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Product/Add",
                            ParentID = 19
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürünler",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Product/Update",
                            ParentID = 19
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürünler",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Product/Delete",
                            ParentID = 19
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürünler",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Product/Detail",
                            ParentID = 19
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürün Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductType/List",
                            ParentID = 18
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürün Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductType/Add",
                            ParentID = 24
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürün Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductType/Update",
                            ParentID = 24
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürün Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductType/Delete",
                            ParentID = 24
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Ürün Tipleri",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/ProductType/Detail",
                            ParentID = 24
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 2,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Genel Sayfalar",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "#"
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 1,
                            IsActive = true,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Hakkımızda",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Contact/List",
                            ParentID = 29
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Hakkımızda",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Contact/Add",
                            ParentID = 30
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Hakkımızda",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Contact/Update",
                            ParentID = 30
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Hakkımızda",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Contact/Delete",
                            ParentID = 30
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 1,
                            IsActive = false,
                            MetaDescription = "",
                            MetaKeywords = "",
                            MetaTitle = "",
                            PageName = "Hakkımızda",
                            PageSeoURL = "",
                            PageTypeID = 1,
                            PageURL = "/Admin/Contact/Detail",
                            ParentID = 30
                        });
                });

            modelBuilder.Entity("Entities.Concrete.PagePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppOperationClaimId")
                        .HasColumnType("int");

                    b.Property<int?>("AppUserTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OperationClaimID")
                        .HasColumnType("int")
                        .HasColumnName("OperationClaimID");

                    b.Property<int>("PageID")
                        .HasColumnType("int")
                        .HasColumnName("PageID");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    b.HasKey("Id");

                    b.HasIndex("AppOperationClaimId");

                    b.HasIndex("AppUserTypeId");

                    b.HasIndex("PageID");

                    b.ToTable("PagePermissions", "dbo");
                });

            modelBuilder.Entity("Entities.Concrete.PageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PageTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PageTypeName");

                    b.HasKey("Id");

                    b.ToTable("PageTypes", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PageTypeName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PageTypeName = "Web"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppUser", b =>
                {
                    b.HasOne("Entities.Concrete.AppUserType", "AppUserType")
                        .WithMany("AppUsers")
                        .HasForeignKey("AppUserTypeId");

                    b.Navigation("AppUserType");
                });

            modelBuilder.Entity("Entities.Concrete.AppUserTypeAppOperationClaim", b =>
                {
                    b.HasOne("Entities.Concrete.AppOperationClaim", "AppOperationClaim")
                        .WithMany("AppUserTypeAppOperationClaims")
                        .HasForeignKey("AppOperationClaimId");

                    b.HasOne("Entities.Concrete.AppUserType", "AppUserType")
                        .WithMany()
                        .HasForeignKey("AppUserTypeId");

                    b.Navigation("AppOperationClaim");

                    b.Navigation("AppUserType");
                });

            modelBuilder.Entity("Entities.Concrete.Page", b =>
                {
                    b.HasOne("Entities.Concrete.PageType", "PageType")
                        .WithMany("Pages")
                        .HasForeignKey("PageTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageType");
                });

            modelBuilder.Entity("Entities.Concrete.PagePermission", b =>
                {
                    b.HasOne("Entities.Concrete.AppOperationClaim", "AppOperationClaim")
                        .WithMany("PagePermissions")
                        .HasForeignKey("AppOperationClaimId");

                    b.HasOne("Entities.Concrete.AppUserType", "AppUserType")
                        .WithMany("PagePermissions")
                        .HasForeignKey("AppUserTypeId");

                    b.HasOne("Entities.Concrete.Page", "Page")
                        .WithMany("PagePermissions")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppOperationClaim");

                    b.Navigation("AppUserType");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Entities.Concrete.AppOperationClaim", b =>
                {
                    b.Navigation("AppUserTypeAppOperationClaims");

                    b.Navigation("PagePermissions");
                });

            modelBuilder.Entity("Entities.Concrete.AppUserType", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("PagePermissions");
                });

            modelBuilder.Entity("Entities.Concrete.Page", b =>
                {
                    b.Navigation("PagePermissions");
                });

            modelBuilder.Entity("Entities.Concrete.PageType", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
